### ISSUE TITLE
[CM] Enable inference for `ResNet-50` with `TVM - TFLite` backend

### ISSUE THREAD

**Issue by KJlaccHoeUM9l** [Deelvin/ck#8]
Based on [this tutorial](https://github.com/mlcommons/ck/blob/master/docs/tutorials/sc22-scc-mlperf-part3.md) for TVM-ONNX (MLPerf inference - Python - ResNet50 FP32 - ImageNet - TVM - CPU - Offline), you need to add the ability to run inference for TVM with `TFLite` frontend.

To run this inference, you need to change `backend` parameter as follows:
```
--backend=tvm-tflite
```
When you select this backend, you will be taken to the corresponding branch in [python script](https://github.com/Deelvin/ck/blob/ac4dfa9caec5fa1fb672c7aea69fcb9b96df6454/cm-mlops/script/get-ml-model-resnet50-tvm/process.py#L94). However, there is no prepared section for `TFLite` in [the configuration file](https://github.com/Deelvin/ck/blob/ac4dfa9caec5fa1fb672c7aea69fcb9b96df6454/cm-mlops/script/app-mlperf-inference-reference/_cm.yaml). Therefore, it must be done by analogy with [ONNX](https://github.com/Deelvin/ck/blob/ac4dfa9caec5fa1fb672c7aea69fcb9b96df6454/cm-mlops/script/app-mlperf-inference-reference/_cm.yaml#L417) and [PyTorch](https://github.com/Deelvin/ck/blob/ac4dfa9caec5fa1fb672c7aea69fcb9b96df6454/cm-mlops/script/app-mlperf-inference-reference/_cm.yaml#L431).

The result of the work should be a prepared PR for the official `CK`.

**Comment by KJlaccHoeUM9l** [comment]
CC @Ailurus1

**Comment by Maximallnyi** [comment]
In process of prototyping new tvm-tflite workflow I got this errors:
![photo_2023-02-13_17-20-10](https://user-images.githubusercontent.com/78957791/218511197-e8ce8d7f-9615-47ab-959f-433a56e3c31b.jpg)
![photo_2023-02-13_17-20-12](https://user-images.githubusercontent.com/78957791/218511244-b667693a-12e3-461b-a178-2ec992ca4f75.jpg)

**Comment by Maximallnyi** [comment]
After fixing some dependencies, the script `get-ml-model-resnet50-tvm/process.py` has become correctly detecting `.tflite` model, however, there were some difficulties with processing the input dimensions:  
```
/usr/bin/python3 /home/max/CM/repos/Deelvin@ck/cm-mlops/script/get-ml-model-resnet50-tvm/process.py
TVM model: /home/max/CM/repos/local/cache/5720a56c114b4387/resnet50_v1.tflite
TVM shape dict: {'input_tensor:0': (32, 3, 224, 224)}
conv2d NHWC layout is not optimized for x86 with autotvm.
conv2d NHWC layout is not optimized for x86 with autotvm.
conv2d NHWC layout is not optimized for x86 with autotvm.
...
```
And there are a lot of lines like this.
But actually the script `get-ml-model-resnet50-tvm/process.py` finishes successfully and goes over inference where catches another one error:
```
INFO:imagenet:Loading 500 preprocessed images using 12 threads
INFO:imagenet:loaded 500 images, cache=0, already_preprocessed=True, took=0.0sec
TVM: loading model /home/max/CM/repos/local/cache/e42ca0290b774f85/model-tvm.so
Traceback (most recent call last):
  File "python/main.py", line 615, in <module>
    main()
  File "python/main.py", line 529, in main
    _ = backend.predict({backend.inputs[0]: img})
  File "/home/max/CM/repos/local/cache/668c89d570a54230/inference/vision/classification_and_detection/python/backend_tvm.py", line 341, in predict
    return self.predict_impl(feed)
  File "/home/max/CM/repos/local/cache/668c89d570a54230/inference/vision/classification_and_detection/python/backend_tvm.py", line 294, in predict_impl
    self.graph.set_input(input_idx, tvm.nd.array(data))
  File "/home/max/.local/lib/python3.8/site-packages/tvm/contrib/graph_executor.py", line 184, in set_input
    v.copyfrom(value)
  File "/home/max/.local/lib/python3.8/site-packages/tvm/runtime/ndarray.py", line 143, in copyfrom
    source_array.copyto(self)
  File "/home/max/.local/lib/python3.8/site-packages/tvm/runtime/ndarray.py", line 251, in copyto
    return self._copyto(target)
  File "/home/max/.local/lib/python3.8/site-packages/tvm/_ffi/_ctypes/ndarray.py", line 90, in _copyto
    check_call(_LIB.TVMArrayCopyFromTo(self.handle, target_nd.handle, None))
  File "/home/max/.local/lib/python3.8/site-packages/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  36: 0xffffffffffffffff
  35: _start
  34: __libc_start_main
  33: Py_BytesMain
  32: Py_RunMain
  31: PyRun_SimpleFileExFlags
  30: 0x000000000067fa70
  29: 0x000000000067f9ce
  28: 0x000000000067f950
  27: PyEval_EvalCode
  26: _PyEval_EvalCodeWithName
  25: _PyEval_EvalFrameDefault
  24: _PyFunction_Vectorcall
  23: _PyEval_EvalCodeWithName
  22: _PyEval_EvalFrameDefault
  21: _PyFunction_Vectorcall
  20: _PyEval_EvalFrameDefault
  19: _PyFunction_Vectorcall
  18: _PyEval_EvalFrameDefault
  17: _PyFunction_Vectorcall
  16: _PyEval_EvalCodeWithName
  15: _PyEval_EvalFrameDefault
  14: _PyFunction_Vectorcall
  13: _PyEval_EvalFrameDefault
  12: _PyFunction_Vectorcall
  11: _PyEval_EvalCodeWithName
  10: _PyEval_EvalFrameDefault
  9: _PyFunction_Vectorcall
  8: _PyEval_EvalFrameDefault
  7: _PyObject_MakeTpCall
  6: 0x00007fd087aac9eb
  5: _ctypes_callproc
  4: 0x00007fd08abd0409
  3: 0x00007fd08abd0ff4
  2: TVMArrayCopyFromTo
  1: tvm::runtime::NDArray::CopyFromTo(DLTensor const*, DLTensor*, void*)
  0: _ZN3tvm7runtime6deta
  File "/workspace/tvm/src/runtime/ndarray.cc", line 270
TVMError:
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------

  Check failed: from_size == to_size (19267584 vs. 602112) : TVMArrayCopyFromTo: The size must exactly match

CM error: Portable CM script failed (name = benchmark-program, return code = 256)
```

**Comment by Maximallnyi** [comment]
There are still problems with `batch_size != 1`, so I manually set it as 1 for debugging. Now compiled model process images properly, but it gives some unexpected output, that causes the following error:
```
ERROR:main:thread: failed on contentid=['/home/max/CM/repos/local/cache/c719b1ebe7d34609/ILSVRC2012_val_00000090.JPEG'], The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
...
ERROR:main:thread: failed on contentid=['/home/max/CM/repos/local/cache/c719b1ebe7d34609/ILSVRC2012_val_00000453.JPEG'], The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "python/main.py", line 615, in <module>
    main()
  File "python/main.py", line 599, in main
    add_results(final_results, "{}".format(scenario),
  File "python/main.py", line 420, in add_results
    buckets = np.percentile(result_list, percentiles).tolist()
  File "<__array_function__ internals>", line 180, in percentile
  File "/usr/local/lib/python3.8/dist-packages/numpy-1.23.4-py3.8-linux-x86_64.egg/numpy/lib/function_base.py", line 4166, in percentile
    return _quantile_unchecked(
  File "/usr/local/lib/python3.8/dist-packages/numpy-1.23.4-py3.8-linux-x86_64.egg/numpy/lib/function_base.py", line 4424, in _quantile_unchecked
    r, k = _ureduce(a,
  File "/usr/local/lib/python3.8/dist-packages/numpy-1.23.4-py3.8-linux-x86_64.egg/numpy/lib/function_base.py", line 3725, in _ureduce
    r = func(a, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/numpy-1.23.4-py3.8-linux-x86_64.egg/numpy/lib/function_base.py", line 4593, in _quantile_ureduce_func
    result = _quantile(arr,
  File "/usr/local/lib/python3.8/dist-packages/numpy-1.23.4-py3.8-linux-x86_64.egg/numpy/lib/function_base.py", line 4699, in _quantile
    take(arr, indices=-1, axis=DATA_AXIS)
  File "<__array_function__ internals>", line 180, in take
  File "/usr/local/lib/python3.8/dist-packages/numpy-1.23.4-py3.8-linux-x86_64.egg/numpy/core/fromnumeric.py", line 190, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/usr/local/lib/python3.8/dist-packages/numpy-1.23.4-py3.8-linux-x86_64.egg/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.

CM error: Portable CM script failed (name = benchmark-program, return code = 256) 
```

**Comment by Maximallnyi** [comment]
I tried to get output from properly working `tvm-onnx` pipeline to compare with output we have with `tvm-tflite`. In the first case output looked like: 
`[array([390, 785, 516, 545, 711, 424, 710, 516, 572, 742, 913, 972, 670,
       495, 891, 560, 824, 551, 760, 419, 704, 162, 997,  44, 818, 741,
       114, 837, 900, 824, 414, 457]), array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)]` 
There are 2 elements: the first looks like labels for images (there are 32 labels as batch_size = 32) and second looks like probabilities for each class. And for `tvm-tflite` I get: 
`[array([[0., 0., 0., ..., 0., 0., 0.]], dtype=float32), array([527], dtype=int32)]`
In some reasons output is reversed. So, I manually reverse it and after this the whole inference workflow finishes successfully but it shows too poor accuracy: 
`accuracy=0.200%, good=1, total=500`

**Comment by Ailurus1** [comment]
Solved [here](https://github.com/mlcommons/inference/pull/1498/files)
